# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apiwithjwt:
    image: apiwithjwt
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5118:5118
